apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset
  labels:
    app: statefulset
    env: dev
spec:
  selector:
    matchLabels:
      app: statefulset
      env: dev
  replicas: 3 
  serviceName: "statefulset-headless"
  template:
    metadata:
      name: statefulset
      labels:
        app: statefulset
        env: dev
    spec:
      restartPolicy: Always
      containers:
      - name: statefulset
        image: alaien/statefulset-test
        imagePullPolicy: Always
        ports:
        - containerPort: 7777
        command: 
        - bash
        - "-c"
        - |
          if [[ `hostname` =~ -([0-9])$ ]] ; then
          export STATEFULSET_ENV_SERVER_TAG=${BASH_REMATCH[1]}
          fi
          env | grep STATEFULSET_ENV_SERVER_TAG
          java -jar web.jar
---

apiVersion: v1
kind: Service
metadata:
  name: statefulset
  labels:
    app: statefulset
    env: dev
spec:
  selector:
    app: statefulset
    env: dev
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 7777


---


apiVersion: v1
kind: Service
metadata:
  name: statefulset-headless
  labels:
    app: statefulset
    env: dev
spec:
  selector:
    app: statefulset
    env: dev
  clusterIP: None
  ports:
  - port: 8000
    targetPort: 7777
