apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
  labels:
    release: stable
    app: jenkins
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: us
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/nfs
    server: cross.mokulive.stream
