kind: Pod
apiVersion: v1
metadata:
  name: mypod
  labels:
    app: test
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: mypd
      ports:
      - name: nginx
        containerPort: 80
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: pvc
