apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    life: dev
spec:
  selector:
    matchLabels:
      app: nginx
      life: dev
  replicas: 1
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        life: dev
    spec:
      restartPolicy: Always
      initContainers:
      - name: nginx-init
        image: nginx
        volumeMounts:
        - mountPath: /html
          name: html
        env:
        - name: PASS
          valueFrom:
            secretKeyRef:
              name: password
              key: password
        command: ['sh','-c','echo $PASS > /html/index.html']
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html
      volumes:
      - name: html
        emptyDir: {}
      - name: password
        secret:
          secretName: password

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
    life: dev
spec:
  selector:
    app: nginx
    life: dev
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
